import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';

const Color primaryColor = Color(0xFFF83758);
const Color campusColor = Color(0xFF202246);
Color secondaryColor = Color(0xFFF5B029);
Color buttonColor = Color(0xFF2F0640);
Color primaryDarkColor = Color(0xFF2F0640);
const Color inputBackgroundColor = Color(0xFFEEEEEE);
Color primaryLightColor = Color(0xFFE6C1F5);
Color darkGreyColor = Color(0xFF424342);
Color inputTextColor = Color(0xFF6A2388);
Color placeHolderColor = Color(0xFFA13DCC);
Color oxbloodColor = const Color(0xFF501717);
Color royalBlueColor = const Color(0xFF1700A3);
Color babyBlueColor = const Color(0xFF00BBF9);
Color darkBrownColor = const Color(0xFF403636);
Color orangeColor = const Color(0xFFFE7F2D);
Color inputTextFillColor = Color(0xfff1f3f2);
Color lightGrey = Color(0xffd0d0d0);
Color veryLightGrey = Color(0xffEEEEEE);
Color kWhiteColor = Colors.white;
Color kLightTextColor = Color(0xff747474);
Color kMainGreen = Color(0xff2ab36c);
Color kCardTextColor = Color(0xfff8f9fd);
Color kTransparentColor = Colors.transparent;
Color kMainTextColor = Color(0xff000000);
Color kIconColor = Color(0xffc4c8c1);
Color kHintColor = Color(0xffa3a3a3);
Color kNavigationButtonColor = Color(0xFF435DA1);
Color kContainerTextColor = Color(0xff606060);
Color kButtonColor = Color(0xfffafafa);
Color kButtonBorderColor = Color(0xffe1e1e1);
Color kButtonTextColor = Color(0xffbababa);
Color kContainerShadowColor = Color(0xff87fddc82);
